version: '3'

services: 
  learner-service:
    build: ./learners
    ports:
      - 5000:80


  website:
    image: php:7-apache
    volumes:
      - ./website:/var/www/html/
    ports:
      - 5002:80
    depends_on:
      - learner-service
